port 26379
sentinel monitor pos54-master redis-master 6379 2
sentinel auth-pass pos54-master pos54-redis-secret
sentinel down-after-milliseconds pos54-master 5000
sentinel failover-timeout pos54-master 10000
sentinel parallel-syncs pos54-master 1
sentinel deny-scripts-reconfig yes
