# ─── 54Link Apache APISIX Gateway Configuration ──────────────────────────────
apisix:
  node_listen: 9080
  enable_ipv6: false
  enable_admin: true
  admin_key:
    - name: admin
      key: ${APISIX_ADMIN_KEY:-edd1c9f034335f136f87ad84b625c8f1}
      role: admin
    - name: viewer
      key: ${APISIX_VIEWER_KEY:-4054f7cf07e344346cd3f287985e76a2}
      role: viewer

deployment:
  admin:
    admin_listen:
      ip: 0.0.0.0
      port: 9180
    admin_api_mtls:
      admin_ssl_ca_cert: ""
      admin_ssl_cert: ""
      admin_ssl_cert_key: ""
    allow_admin:
      - 127.0.0.0/24
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16

  etcd:
    host:
      - "http://apisix-etcd:2379"
    prefix: /apisix
    timeout: 30

plugin_attr:
  prometheus:
    export_uri: /apisix/prometheus/metrics
    export_addr:
      ip: "0.0.0.0"
      port: 9091
    metric_prefix: apisix_
    enable_export_server: true

  log-rotate:
    interval: 3600
    max_kept: 168

plugins:
  - real-ip
  - ai
  - client-control
  - proxy-control
  - request-id
  - zipkin
  - ext-plugin-pre-req
  - fault-injection
  - mocking
  - serverless-pre-function
  - cors
  - ip-restriction
  - ua-restriction
  - referer-restriction
  - csrf
  - uri-blocker
  - request-validation
  - openid-connect
  - cas-auth
  - authz-casbin
  - authz-casdoor
  - wolf-rbac
  - ldap-auth
  - hmac-auth
  - basic-auth
  - jwt-auth
  - key-auth
  - consumer-restriction
  - forward-auth
  - opa
  - authz-keycloak
  - proxy-mirror
  - proxy-cache
  - proxy-rewrite
  - api-breaker
  - limit-conn
  - limit-count
  - limit-req
  - gzip
  - server-info
  - traffic-split
  - redirect
  - response-rewrite
  - kafka-logger
  - http-logger
  - splunk-hec-logging
  - skywalking-logger
  - google-cloud-logging
  - sls-logger
  - tcp-logger
  - udp-logger
  - file-logger
  - clickhouse-logger
  - tencent-cloud-cls
  - inspect
  - example-plugin
  - aws-lambda
  - azure-functions
  - openwhisk
  - openfunction
  - serverless-post-function
  - ext-plugin-post-req
  - ext-plugin-post-resp
  - prometheus
  - node-status
  - datadog
  - echo
  - loggly
  - elasticsearch-logger
  - rocketmq-logger
  - syslog
  - log-rotate
  - real-ip
  - ext-plugin-pre-req
  - grpc-transcode
  - grpc-web
  - public-api
  - skywalking
  - opentelemetry
  - ocsp-stapling
  - multi-auth
  - body-transformer
  - attach-consumer-label
