apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: 54link-dapr-config
  namespace: default
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://jaeger.54link.io:9411/api/v2/spans"
  metric:
    enabled: true
  logging:
    apiLogging:
      enabled: true
      obfuscateURLs: false
      omitHealthChecks: true
  features:
    - name: Actor.TypeMetadata
      enabled: true
    - name: PubSub.SendBulkMessagesWhenSubscribersNotFound
      enabled: false
  api:
    allowed:
      - name: invoke
        version: v1
      - name: state
        version: v1
      - name: pubsub
        version: v1
      - name: secrets
        version: v1
      - name: actors
        version: v1
