/**
 * Trip Summary Router
 * Generates a tourist trip summary report (HTML → S3) covering QR payments,
 * loyalty points earned, and establishments visited within a date range.
 */
import { protectedProcedure, router } from "../_core/trpc";
import { getDb } from "../db";
import { z } from "zod";
import { sql, eq, and, gte, lte, desc } from "drizzle-orm";
import {
  qrPaymentTokens,
  establishments,
  loyaltyTransactions,
  touristTripSummaries,
} from "../../drizzle/schema";
import { TRPCError } from "@trpc/server";
import { storagePut } from "../storage";
import { createUserNotification } from "../db";

// ── HTML report renderer ──────────────────────────────────────────────────────

interface PaymentRow {
  establishmentName: string;
  amountUsd: number;
  paidAt: Date | null;
  description: string | null;
}

function renderTripSummaryHtml(opts: {
  userName: string;
  dateFrom: Date;
  dateTo: Date;
  payments: PaymentRow[];
  totalSpentUsd: number;
  totalPointsEarned: number;
  uniqueEstablishments: string[];
}): string {
  const fmt = (d: Date) =>
    d.toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
    });
  const fmtCurrency = (n: number) =>
    new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(n);

  const paymentRows = opts.payments
    .map(
      (p) => `
    <tr>
      <td>${p.paidAt ? fmt(p.paidAt) : "—"}</td>
      <td>${escHtml(p.establishmentName)}</td>
      <td>${escHtml(p.description ?? "QR Payment")}</td>
      <td style="text-align:right">${fmtCurrency(p.amountUsd)}</td>
    </tr>`
    )
    .join("");

  const estList = opts.uniqueEstablishments
    .map((n) => `<li>${escHtml(n)}</li>`)
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>TourismPay Trip Summary</title>
<style>
  body { font-family: Arial, sans-serif; color: #1a1a2e; margin: 0; padding: 0; background: #f4f6fb; }
  .header { background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%); color: #fff; padding: 40px; }
  .header h1 { margin: 0 0 8px; font-size: 28px; }
  .header p { margin: 0; opacity: 0.7; font-size: 14px; }
  .content { padding: 32px 40px; }
  .stats { display: flex; gap: 24px; margin-bottom: 32px; flex-wrap: wrap; }
  .stat-card { background: #fff; border-radius: 12px; padding: 20px 28px; flex: 1; min-width: 160px;
               box-shadow: 0 2px 8px rgba(0,0,0,0.08); }
  .stat-card .value { font-size: 28px; font-weight: 700; color: #4f46e5; }
  .stat-card .label { font-size: 12px; color: #6b7280; margin-top: 4px; text-transform: uppercase; letter-spacing: 0.05em; }
  table { width: 100%; border-collapse: collapse; background: #fff; border-radius: 12px;
          overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.08); margin-bottom: 32px; }
  th { background: #f8fafc; padding: 12px 16px; text-align: left; font-size: 12px;
       text-transform: uppercase; letter-spacing: 0.05em; color: #6b7280; border-bottom: 1px solid #e5e7eb; }
  td { padding: 12px 16px; border-bottom: 1px solid #f3f4f6; font-size: 14px; }
  tr:last-child td { border-bottom: none; }
  .section-title { font-size: 18px; font-weight: 600; margin: 0 0 16px; color: #1a1a2e; }
  ul { background: #fff; border-radius: 12px; padding: 20px 20px 20px 36px;
       box-shadow: 0 2px 8px rgba(0,0,0,0.08); margin: 0 0 32px; }
  ul li { padding: 4px 0; font-size: 14px; }
  .footer { text-align: center; padding: 24px; font-size: 12px; color: #9ca3af; }
</style>
</head>
<body>
<div class="header">
  <h1>Trip Summary Report</h1>
  <p>${escHtml(opts.userName)} &nbsp;·&nbsp; ${fmt(opts.dateFrom)} – ${fmt(opts.dateTo)}</p>
</div>
<div class="content">
  <div class="stats">
    <div class="stat-card">
      <div class="value">${fmtCurrency(opts.totalSpentUsd)}</div>
      <div class="label">Total Spent</div>
    </div>
    <div class="stat-card">
      <div class="value">${opts.totalPointsEarned.toLocaleString()}</div>
      <div class="label">Points Earned</div>
    </div>
    <div class="stat-card">
      <div class="value">${opts.payments.length}</div>
      <div class="label">Payments Made</div>
    </div>
    <div class="stat-card">
      <div class="value">${opts.uniqueEstablishments.length}</div>
      <div class="label">Places Visited</div>
    </div>
  </div>

  <p class="section-title">Payment History</p>
  <table>
    <thead><tr><th>Date</th><th>Establishment</th><th>Description</th><th style="text-align:right">Amount</th></tr></thead>
    <tbody>${paymentRows || '<tr><td colspan="4" style="text-align:center;color:#9ca3af">No payments in this period</td></tr>'}</tbody>
  </table>

  <p class="section-title">Places Visited</p>
  <ul>${estList || "<li>No establishments visited</li>"}</ul>
</div>
<div class="footer">Generated by TourismPay &nbsp;·&nbsp; ${new Date().toUTCString()}</div>
</body>
</html>`;
}

function escHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

// ── Router ────────────────────────────────────────────────────────────────────

export const tripSummaryRouter = router({
  /** Generate a trip summary report for the given date range and upload to S3. */
  generate: protectedProcedure
    .input(
      z.object({
        dateFrom: z.number().int().positive(), // UTC ms
        dateTo: z.number().int().positive(),   // UTC ms
      })
    )
    .mutation(async ({ ctx, input }) => {
      const db = await getDb();
      if (!db)
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Database unavailable",
        });

      const fromDate = new Date(input.dateFrom);
      const toDate = new Date(input.dateTo);

      if (fromDate >= toDate) {
        throw new TRPCError({
          code: "BAD_REQUEST",
          message: "dateFrom must be before dateTo",
        });
      }

      // 1. Fetch QR payments in range
      const payments = await db
        .select({
          amountUsd: qrPaymentTokens.amountUsd,
          paidAt: qrPaymentTokens.paidAt,
          description: qrPaymentTokens.description,
          establishmentName: establishments.name,
        })
        .from(qrPaymentTokens)
        .leftJoin(
          establishments,
          eq(qrPaymentTokens.establishmentId, establishments.id)
        )
        .where(
          and(
            eq(qrPaymentTokens.paidByUserId, ctx.user.id),
            eq(qrPaymentTokens.status, "paid"),
            gte(qrPaymentTokens.paidAt, fromDate),
            lte(qrPaymentTokens.paidAt, toDate)
          )
        )
        .orderBy(desc(qrPaymentTokens.paidAt))
        .limit(500);

      // 2. Fetch loyalty points earned in range (loyaltyTransactions uses integer Unix-second timestamps)
      const fromSec = Math.floor(input.dateFrom / 1000);
      const toSec = Math.floor(input.dateTo / 1000);
      const loyaltyRows = await db
        .select({ points: loyaltyTransactions.points })
        .from(loyaltyTransactions)
        .where(
          and(
            eq(loyaltyTransactions.userId, String(ctx.user.id)),
            eq(loyaltyTransactions.type, "earn"),
            gte(loyaltyTransactions.createdAt, fromSec),
            lte(loyaltyTransactions.createdAt, toSec)
          )
        );

      const totalSpentUsd = payments.reduce(
        (s, p) => s + parseFloat(String(p.amountUsd ?? "0")),
        0
      );
      const totalPointsEarned = loyaltyRows.reduce(
        (s, r) => s + (r.points ?? 0),
        0
      );
      const uniqueEstablishments = Array.from(
        new Set(payments.map((p) => p.establishmentName ?? "Unknown"))
      );

      // 3. Render HTML report
      const html = renderTripSummaryHtml({
        userName: ctx.user.name ?? ctx.user.email ?? `User #${ctx.user.id}`,
        dateFrom: fromDate,
        dateTo: toDate,
        payments: payments.map((p) => ({
          establishmentName: p.establishmentName ?? "Unknown",
          amountUsd: parseFloat(String(p.amountUsd ?? "0")),
          paidAt: p.paidAt,
          description: p.description,
        })),
        totalSpentUsd,
        totalPointsEarned,
        uniqueEstablishments,
      });

      // 4. Upload to S3
      const suffix = Math.random().toString(36).slice(2, 8);
      const fileKey = `trip-summaries/${ctx.user.id}/${Date.now()}-${suffix}.html`;
      const { url } = await storagePut(
        fileKey,
        Buffer.from(html, "utf-8"),
        "text/html"
      );

      // 5. Persist record
      const [record] = await db
        .insert(touristTripSummaries)
        .values({
          userId: ctx.user.id,
          dateFrom: fromDate,
          dateTo: toDate,
          totalSpentUsd: String(totalSpentUsd.toFixed(6)),
          totalPointsEarned,
          paymentCount: payments.length,
          establishmentCount: uniqueEstablishments.length,
          reportUrl: url,
          reportKey: fileKey,
        })
        .returning();

      // 6. Notify user
      await createUserNotification({
        userId: ctx.user.id,
        category: "report",
        title: "Trip summary ready",
        content: `Your trip summary (${payments.length} payments, $${totalSpentUsd.toFixed(2)} spent) is ready to download.`,
        actionUrl: url,
        actionLabel: "Download Report",
      });

      return {
        id: record.id,
        reportUrl: url,
        totalSpentUsd,
        totalPointsEarned,
        paymentCount: payments.length,
        establishmentCount: uniqueEstablishments.length,
      };
    }),

  /** List past trip summary reports for the current user. */
  list: protectedProcedure.query(async ({ ctx }) => {
    const db = await getDb();
    if (!db) return [];
    return db
      .select()
      .from(touristTripSummaries)
      .where(eq(touristTripSummaries.userId, ctx.user.id))
      .orderBy(desc(touristTripSummaries.createdAt))
      .limit(20);
  }),
});
