apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: "redis-master.dapr-infra.svc.cluster.local:6379"
  - name: redisPassword
    secretKeyRef:
      name: redis-secret
      key: redis-password
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: "kafka-broker-1.dapr-infra.svc.cluster.local:9092,kafka-broker-2.dapr-infra.svc.cluster.local:9092"
  - name: consumerGroup
    value: "payment-service-group"
  - name: authRequired
    value: "true"
  - name: saslUsername
    secretKeyRef:
      name: kafka-secret
      key: username
  - name: saslPassword
    secretKeyRef:
      name: kafka-secret
      key: password
  - name: saslType
    value: "SCRAM-SHA-512"
  - name: initialOffset
    value: "newest"
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
  - name: name
    value: "dapr-secrets"
