apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: erpnext-pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: "kafka.internal.svc.cluster.local:9092"
  - name: consumerGroup
    value: "erpnext-integration-group"
  - name: authRequired
    value: "false"
  - name: disableTls
    value: "true"
  - name: maxMessageBytes
    value: "1048576"
  - name: clientID
    value: "erpnext-integration-service"
