/**
 * ItineraryPDF — Export itinerary as PDF using jsPDF.
 * Generates a formatted document with day timelines, costs, and merchant info.
 */
import { Button } from "@/components/ui/button";
import { FileDown, Share2 } from "lucide-react";
import { toast } from "sonner";

interface ItineraryItem {
  time_slot: string;
  start_time: string;
  end_time: string;
  title: string;
  description: string;
  merchant_name: string;
  cost_usd: number;
  item_type: string;
  bookable: boolean;
}

interface ItineraryDay {
  day_number: number;
  title: string;
  items: ItineraryItem[];
}

interface GeneratedTrip {
  destination: string;
  country: string;
  durationDays: number;
  totalCostUsd: number;
  dailyAverageUsd: number;
  days: ItineraryDay[];
  tips: string[];
  merchantCoverage: number;
}

interface ItineraryPDFProps {
  trip: GeneratedTrip;
}

export function ItineraryPDF({ trip }: ItineraryPDFProps) {
  const exportPDF = async () => {
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF();

      const pageWidth = doc.internal.pageSize.getWidth();
      let y = 20;

      // Header
      doc.setFontSize(20);
      doc.setFont("helvetica", "bold");
      doc.text("TourismPay Trip Itinerary", pageWidth / 2, y, { align: "center" });
      y += 12;

      // Destination info
      doc.setFontSize(14);
      doc.text(`${trip.destination}, ${trip.country}`, pageWidth / 2, y, { align: "center" });
      y += 8;

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(
        `${trip.durationDays} days | $${trip.totalCostUsd.toFixed(0)} total | $${trip.dailyAverageUsd.toFixed(0)}/day | ${trip.merchantCoverage}% TourismPay`,
        pageWidth / 2, y, { align: "center" }
      );
      y += 12;

      // Separator line
      doc.setDrawColor(200);
      doc.line(20, y, pageWidth - 20, y);
      y += 10;

      // Days
      for (const day of trip.days) {
        // Check if we need a new page
        if (y > 260) {
          doc.addPage();
          y = 20;
        }

        const dayCost = day.items.reduce((s, i) => s + (i.cost_usd ?? 0), 0);

        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.text(`Day ${day.day_number}: ${day.title}`, 20, y);
        doc.setFont("helvetica", "normal");
        doc.text(`$${dayCost.toFixed(0)}`, pageWidth - 20, y, { align: "right" });
        y += 7;

        // Items
        for (const item of day.items) {
          if (y > 270) {
            doc.addPage();
            y = 20;
          }

          doc.setFontSize(9);
          doc.setFont("helvetica", "normal");

          const timeStr = `${item.start_time}–${item.end_time}`;
          const merchantStr = item.merchant_name ? ` @ ${item.merchant_name}` : "";
          const bookableStr = item.bookable ? " [TourismPay]" : "";
          const line = `  ${timeStr}  ${item.title}${merchantStr}${bookableStr} — $${item.cost_usd.toFixed(2)}`;

          doc.text(line, 24, y);
          y += 5;
        }

        y += 5;
      }

      // Tips section
      if (trip.tips && trip.tips.length > 0) {
        if (y > 240) {
          doc.addPage();
          y = 20;
        }

        y += 5;
        doc.setDrawColor(200);
        doc.line(20, y, pageWidth - 20, y);
        y += 8;

        doc.setFontSize(11);
        doc.setFont("helvetica", "bold");
        doc.text("Travel Tips", 20, y);
        y += 7;

        doc.setFontSize(9);
        doc.setFont("helvetica", "normal");
        for (const tip of trip.tips) {
          if (y > 275) {
            doc.addPage();
            y = 20;
          }
          doc.text(`• ${tip}`, 24, y);
          y += 5;
        }
      }

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(128);
      doc.text(
        `Generated by TourismPay AI Trip Planner — ${new Date().toLocaleDateString()}`,
        pageWidth / 2,
        doc.internal.pageSize.getHeight() - 10,
        { align: "center" }
      );

      // Save
      const filename = `TourismPay-${trip.destination.replace(/\s+/g, "-")}-${trip.durationDays}days.pdf`;
      doc.save(filename);
      toast.success("PDF exported", { description: filename });
    } catch (err) {
      toast.error("PDF export failed", { description: String(err) });
    }
  };

  const shareItinerary = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: `${trip.destination} Trip — ${trip.durationDays} days`,
          text: `Check out my ${trip.durationDays}-day trip to ${trip.destination}! Total: $${trip.totalCostUsd.toFixed(0)}. Planned with TourismPay AI Trip Planner.`,
          url: window.location.href,
        });
      } catch {
        // User cancelled share
      }
    } else {
      // Fallback: copy to clipboard
      const text = `${trip.destination} (${trip.durationDays} days, $${trip.totalCostUsd.toFixed(0)}) — Planned with TourismPay AI Trip Planner`;
      await navigator.clipboard.writeText(text);
      toast.success("Copied to clipboard");
    }
  };

  return (
    <div className="flex gap-2">
      <Button variant="outline" size="sm" onClick={exportPDF}>
        <FileDown className="w-3.5 h-3.5 mr-1" /> PDF
      </Button>
      <Button variant="outline" size="sm" onClick={shareItinerary}>
        <Share2 className="w-3.5 h-3.5 mr-1" /> Share
      </Button>
    </div>
  );
}
