apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: 54link-cron-daily
  namespace: default
spec:
  type: bindings.cron
  version: v1
  metadata:
    - name: schedule
      value: "@daily"
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: 54link-cron-hourly
  namespace: default
spec:
  type: bindings.cron
  version: v1
  metadata:
    - name: schedule
      value: "@hourly"
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: 54link-cron-settlement
  namespace: default
spec:
  type: bindings.cron
  version: v1
  metadata:
    - name: schedule
      # Run settlement sweep every 15 minutes
      value: "@every 15m"
