apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: 54link-email
  namespace: default
spec:
  type: bindings.smtp
  version: v1
  metadata:
    - name: host
      value: "smtp.54link.io"
    - name: port
      value: "587"
    - name: user
      secretKeyRef:
        name: smtp-secret
        key: username
    - name: password
      secretKeyRef:
        name: smtp-secret
        key: password
    - name: skipTLSVerify
      value: "false"
    - name: emailFrom
      value: "noreply@54link.io"
