apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: 54link-pubsub
  namespace: default
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: "kafka.54link.io:9092"
    - name: consumerGroup
      value: "54link-dapr-consumers"
    - name: authRequired
      value: "false"
    - name: maxMessageBytes
      value: "1048576"
    - name: consumeRetryInterval
      value: "200ms"
    - name: version
      value: "2.0.0"
    - name: disableTls
      value: "false"
    - name: clientID
      value: "54link-dapr-pubsub"
