apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: 54link-secrets
  namespace: default
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:
    - name: vaultAddr
      value: "http://vault.54link.io:8200"
    - name: skipVerify
      value: "false"
    - name: tlsServerName
      value: "vault.54link.io"
    - name: vaultTokenMountPath
      value: "/var/run/secrets/dapr.io/vault/token"
    - name: vaultKVPrefix
      value: "secret"
    - name: vaultKVUsePrefix
      value: "true"
    - name: enginePath
      value: "secret"
    - name: vaultValueType
      value: "map"
