apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: 54link-sms
  namespace: default
spec:
  type: bindings.http
  version: v1
  metadata:
    - name: url
      value: "https://api.ng.termii.com/api/sms/send"
    - name: method
      value: "POST"
    - name: headers
      value: '{"Content-Type":"application/json"}'
    - name: errorIfNotFound
      value: "false"
    - name: waitForResponseHeader
      value: "false"
