apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: 54link-statestore
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: "redis.54link.io:6379"
    - name: redisPassword
      secretKeyRef:
        name: redis-secret
        key: password
    - name: actorStateStore
      value: "true"
    - name: enableTLS
      value: "false"
    - name: maxRetries
      value: "3"
    - name: maxRetryBackoff
      value: "1000ms"
    - name: ttlInSeconds
      value: "86400"
