/*
gen-manifest — 54Link POS Installer Build Tool
================================================
Computes SHA-256 checksums for all embedded service binaries and prints
the Go source snippet that should replace the integrityManifest variable
in cmd/installer/main.go.

Usage (from the installer/ directory):
  go run ./scripts/gen-manifest/main.go

Output is printed to stdout. Paste it into main.go to lock the checksums.

Typical CI workflow:
  1. Build the three service binaries (resilience-agent, offline-queue, analytics-service)
  2. Copy them into installer/cmd/installer/embedded/
  3. Run this script to generate the manifest
  4. Paste the output into main.go
  5. Build the installer: go build -o bin/54link-installer ./cmd/installer/
*/

package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
)

var embeddedBinaries = []string{
	"embedded/resilience-agent",
	"embedded/offline-queue",
	"embedded/analytics-service",
}

func main() {
	// Determine the embedded dir relative to this script
	// When run as `go run ./scripts/gen-manifest/main.go` from installer/,
	// the working directory is installer/
	// The binaries live in installer/cmd/installer/embedded/
	baseDir := filepath.Join("cmd", "installer")

	fmt.Println("// integrityManifest — generated by scripts/gen-manifest/main.go")
	fmt.Println("// DO NOT EDIT MANUALLY")
	fmt.Println("var integrityManifest = map[string]string{")

	allOK := true
	for _, rel := range embeddedBinaries {
		fullPath := filepath.Join(baseDir, rel)
		data, err := os.ReadFile(fullPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "WARNING: cannot read %s: %v (using placeholder)\n", fullPath, err)
			fmt.Printf("\t%q: %q, // MISSING — build pipeline must supply this binary\n", rel, "")
			allOK = false
			continue
		}
		sum := sha256.Sum256(data)
		hash := hex.EncodeToString(sum[:])
		fmt.Printf("\t%q: %q,\n", rel, hash)
	}

	fmt.Println("}")

	if !allOK {
		fmt.Fprintln(os.Stderr, "\n⚠️  Some binaries were missing. Placeholders were used.")
		fmt.Fprintln(os.Stderr, "   Ensure all binaries are present before building a production installer.")
		os.Exit(1)
	}
}
