import { sql } from "drizzle-orm";
import crypto from "crypto";

function uuid() { return crypto.randomUUID(); }
function randomInt(min: number, max: number) { return Math.floor(Math.random() * (max - min + 1)) + min; }
function randomDate(daysBack: number) {
  const d = new Date();
  d.setDate(d.getDate() - randomInt(0, daysBack));
  return d;
}
function randomElement<T>(arr: T[]): T { return arr[Math.floor(Math.random() * arr.length)]; }

export async function seedRemainingTables(db: any, schema: any) {
  console.log("  Checking and seeding remaining tables...");
  
  const tablesToSeed = [
    "walletTransactions",
    "walletBalanceAlerts",
    "loyaltyAccounts",
    "loyaltyTransactions",
    "loyaltyRewards",
    "financeRequests",
    "biometricEnrollments",
    "didDocuments",
    "verifiableCredentials",
    "carbonOffsets",
    "meshTransactions",
    "walletSpendingLimits",
    "pinLockoutHistory",
    "serviceHealthAlerts",
    "serviceHealthHistory",
    "bisTimeline",
    "psKillSwitchState",
    "trustedDevices",
    "loginHistory",
    "rateAlerts",
    "psApiKeys",
    "psTwoFactorSettings",
    "psNotificationChannels",
    "psReminderEmails",
    "psAccountRecovery",
    "bisAutoFlagConfig",
    "touristProfiles",
    "qrPaymentTokens",
    "touristOnboardingState",
    "rolePermissions",
    "pushSubscriptions",
    "merchantPayoutSchedules",
    "touristTripSummaries",
    "touristReviews",
    "reviewSentimentCache",
    "touristDeals",
    "touristItineraries",
    "touristBudgets",
    "touristConciergeSessions",
    "touristTopups",
    "touristDealRedemptions",
    "touristDealWishlists",
    "touristItineraryItems",
    "itineraryCollaborators",
    "itineraryChangelog",
    "lpApplications",
    "lpProviders",
    "lpPositions",
    "lpRewards",
    "lpPoolSnapshots",
    "lpWithdrawals",
    "lpRebalanceEvents",
    "smartContractDeployments",
    "smartContractEvents",
    "insurancePolicies",
    "insuranceClaims",
    "dataExportRequests",
    "dataErasureRequests",
    "loyaltyBalances",
    "loyaltyConversions",
    "tourismPassesTable",
    "socialPosts",
    "flashDeals",
    "referralRewards",
    "merchantInventory",
    "merchantLocations",
    "merchantSplitPayments",
    "wireTransferOrders",
    "agentsTable",
    "agentFloatBalances",
    "cashLoadOrders",
    "partnerQuotes",
    "partnerTransfers",
    "ussdSessions",
    "ussdTransactions",
    "agentKycVerifications",
    "billPayments",
    "virtualCards",
    "virtualCardTransactions",
    "bankTransfersOut",
    "savedBeneficiaries",
    "paymentLinks",
    "splitBills",
    "splitBillParticipants",
    "moneyRequests",
    "rideBookings",
    "nfcPaymentTokens",
    "bankTravelNotifications",
    "esimOrders",
    "agentKioskRegistry",
    "currencyCorridors",
    "preTravelChecklists",
    "kycFastTrackHistory",
    "offlineTokenRenewals",
    "countryRiskCache",
    "travelRiskAssessments",
    "tripPlannerSessions",
    "tripPlannerMessages",
    "tripPlannerRecommendations",
    "tipTransactions",
    "tipDistributionLog",
    "tipConfigs",
    "taxCollections",
    "taxRemittanceTracker",
    "taxRulesCustom",
    "taxReceipts",
    "multiTipGroups",
    "multiTipRecipients",
    "gdsBookingTaxes",
    "gdsStaffTips",
    "gdsLoyaltyEarnings",
    "gdsItineraryConversions",
    "gdsDemandForecasts",
    "taxRules",
    "killSwitchSchedules",
    "temporalWorkflowExecutions",
    "daprSubscriptions",
    "daprStateEntries",
    "fluvioConsumerOffsets",
    "lakehouseEtlRuns",
    "openappsecWafEvents",
    "keycloakSessionTokens",
    "enairaWallets",
    "enairaTransactions",
    "cbnMerchantRegistrations",
    "apisixRouteRegistry",
    "daprSidecarHealth",
    "supervisorAgents",
    "agentAchievements",
    "agentBankAccounts",
    "agentGeofenceZones",
    "agentLoans",
    "agentOnboardingProgress",
    "agentPerformanceScores",
    "agentPushSubscriptions",
    "agentSuspensionLog",
    "commissionAuditTrail",
    "commissionCascadeHistory",
    "commissionClawbacks",
    "commissionPayouts",
    "commissionRules",
    "commissionSplits",
    "commissionTiers",
    "analyticsDashboards",
    "analyticsMetrics",
    "biReportDefinitions",
    "pnlReports",
    "apiKeyUsage",
    "webhookSecrets",
    "auditLog",
    "complianceChecks",
    "complianceFilings",
    "complianceReports",
    "dataConsentRecords",
    "billingAuditLog",
    "billingProvisioningHistory",
    "billingRevenuePeriods",
    "billingRoleAssignments",
    "platformBillingLedger",
    "tenantBillingConfig",
    "tenantBranding",
    "tenantFeatureToggles",
    "tenantFeeOverrides",
    "tenantUsers",
    "biometricAuditEvents",
    "faceEnrollments",
    "fido2Challenges",
    "fido2Credentials",
    "otpTokens",
    "chatMessages",
    "chatSessions",
    "notificationDispatchLog",
    "emailQueue",
    "creditApplications",
    "creditScoreHistory",
    "glEntries",
    "vatRecords",
    "customers",
    "customerJourneySteps",
    "referrals",
    "devices",
    "deviceLocations",
    "geoFences",
    "geofenceZones",
    "mdmGeofenceViolations",
    "disputes",
    "disputeEvidence",
    "disputeMessages",
    "refunds",
    "reversalRequests",
    "ecommerceCartItems",
    "ecommerceCarts",
    "ecommerceCategories",
    "ecommerceInventory",
    "ecommerceOrderItems",
    "ecommerceOrders",
    "ecommerceProducts",
    "erpConfig",
    "erpSyncLog",
    "mqttBridgeConfig",
    "feeAuditTrail",
    "feeRules",
    "rateLimitRules",
    "velocityLimits",
    "floatReconciliations",
    "floatTopUpRequests",
    "reconciliationBatches",
    "reconciliationItems",
    "settlementReconciliation",
    "fraudMlScores",
    "txMonitoringAlerts",
    "observabilityAlerts",
    "dlqMessages",
    "inventoryItems",
    "receiptTemplates",
    "storefrontAds",
    "kycDocuments",
    "kycSessions",
    "merchantKycDocs",
    "loyaltyHistory",
    "merchantKybDocuments",
    "merchantPayouts",
    "merchantSettlements",
    "terminalGroups",
    "multiSimProfiles",
    "simOrchestratorConfig",
    "platformSettings",
    "systemConfig",
    "backupSnapshots",
    "loadTestRuns",
    "serviceRecords",
    "softwareUpdates",
    "qrCodes",
    "shareableLinks",
    "guideFeedback",
    "trainingCourses",
    "trainingEnrollments",
    "workflowDefinitions",
    "workflowInstances",
    "dataExportJobs",
    "erpIntegrations",
    "mqttBrokers",
    "tenantSubscriptions",
    "webhookDeliveries",
    "mdmDevices",
    "agentFloatLoans",
    "tenantActivityLogs",
    "establishmentsasestablishmentsTable",
    "loadTestScenarios",
    "agentOnboardingSteps",
    "sla_definitions",
    "sla_breaches",
    "loadTestRunsasloadTestRunsTable",
    "agentBadges",
    "emailDeliveryLog",
    "encryptedFields",
    "dataRightsRequests",
    "glAccounts",
    "gl_journal_entries",
    "deviceCommands",
    "deviceCompliancePolicies",
    "deviceComplianceViolations",
    "otaReleases",
    "otaUpdateLog",
    "connectivityLog",
    "simFailoverLog",
    "simProbeLog",
    "aiConversations",
    "productBundles",
    "carriers",
  ];
  
  let seededCount = 0;
  
  for (const tableName of tablesToSeed) {
    if (!schema[tableName]) continue;
    
    try {
      // Check if table is empty
      const countRes = await db.select({ count: sql`count(*)` }).from(schema[tableName]);
      const count = Number(countRes[0]?.count || 0);
      
      if (count === 0) {
        // We'll skip complex relational seeding for these generic tables
        // and just let the specific seeders handle the important ones.
        // This is a placeholder for where a generic reflection-based seeder would go.
        seededCount++;
      }
    } catch (e) {
      // Table might not exist or other error
    }
  }
  
  console.log(`  ✓ Checked ${tablesToSeed.length} tables, ${seededCount} were empty`);
}
