// TourismPay eBPF Loader
//
// Loads and manages the eBPF programs for:
//  1. Wallet rate limiter (XDP + TC)
//  2. Fraud signal detector (TC ingress/egress)
//
// Bridges eBPF perf events to the fraud-detection-go service via gRPC,
// and exposes eBPF map metrics to Prometheus.
//
// Usage: ./ebpf-loader --iface eth0 --fraud-grpc localhost:50051
//
// Requires: Linux 5.8+, CAP_BPF, CAP_NET_ADMIN, CAP_SYS_ADMIN
// Build: CGO_ENABLED=0 go build -o ebpf-loader ./loader/

package main

import (
	"context"
	"encoding/binary"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"net"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"
	"unsafe"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/perf"
	"github.com/cilium/ebpf/rlimit"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

// ─── eBPF Map Keys/Values (must match C structs) ──────────────────────────────

type RateBucket struct {
	LastRefillNs   uint64
	Tokens         uint32
	RequestsTotal  uint32
	RequestsDropped uint32
	IsBlocked      uint8
	Pad            [3]uint8
}

type FraudSignal struct {
	TimestampNs uint64
	SrcIP       uint32
	DstIP       uint32
	DstPort     uint16
	SignalType  uint8
	Severity    uint8
	Count       uint32
	UserIDHash  uint64
	Path        [64]byte
}

type MetricKey uint32

const (
	MetricTotalPackets    MetricKey = 0
	MetricAllowedPackets  MetricKey = 1
	MetricRateLimited     MetricKey = 2
	MetricBlacklisted     MetricKey = 3
	MetricSynFloodBlocked MetricKey = 4
	MetricWalletRequests  MetricKey = 5
	MetricDebitRequests   MetricKey = 6
)

// ─── Signal types ─────────────────────────────────────────────────────────────

const (
	SignalVelocityAnomaly    = 1
	SignalPortScan           = 2
	SignalDataExfiltration   = 3
	SignalLateralMovement    = 4
	SignalCredentialStuffing = 5
	SignalLargeTransfer      = 6
)

var signalNames = map[uint8]string{
	SignalVelocityAnomaly:    "velocity_anomaly",
	SignalPortScan:           "port_scan",
	SignalDataExfiltration:   "data_exfiltration",
	SignalLateralMovement:    "lateral_movement",
	SignalCredentialStuffing: "credential_stuffing",
	SignalLargeTransfer:      "large_transfer",
}

// ─── Prometheus metrics ───────────────────────────────────────────────────────

var (
	packetsTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "tourismpay_ebpf_packets_total",
		Help: "Total packets processed by eBPF programs",
	}, []string{"action"})

	fraudSignalsTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "tourismpay_ebpf_fraud_signals_total",
		Help: "Fraud signals detected by eBPF programs",
	}, []string{"signal_type", "severity"})

	blacklistedIPs = prometheus.NewGauge(prometheus.GaugeOpts{
		Name: "tourismpay_ebpf_blacklisted_ips",
		Help: "Number of currently blacklisted IP addresses",
	})

	rateLimitedRequests = prometheus.NewCounter(prometheus.CounterOpts{
		Name: "tourismpay_ebpf_rate_limited_requests_total",
		Help: "Requests dropped by eBPF rate limiter",
	})
)

func init() {
	prometheus.MustRegister(packetsTotal, fraudSignalsTotal, blacklistedIPs, rateLimitedRequests)
}

// ─── eBPF Objects (generated by bpf2go) ──────────────────────────────────────

type WalletRatelimitObjects struct {
	WalletRateMap  *ebpf.Map
	UserDebitMap   *ebpf.Map
	BlacklistMap   *ebpf.Map
	MetricsMap     *ebpf.Map
	SynFloodMap    *ebpf.Map
	TourismpaySXdpDdos        *ebpf.Program
	TourismpaySsTcWalletFilter *ebpf.Program
}

type FraudDetectorObjects struct {
	FraudEvents     *ebpf.Map
	VelocityMap     *ebpf.Map
	AuthFailureMap  *ebpf.Map
	AllowedEgressMap *ebpf.Map
	TourismpaySsFraudEgress  *ebpf.Program
	TourismpaySsFraudIngress *ebpf.Program
}

// ─── Fraud event forwarding ───────────────────────────────────────────────────

type FraudEventPayload struct {
	TimestampNs uint64  `json:"timestamp_ns"`
	SrcIP       string  `json:"src_ip"`
	DstIP       string  `json:"dst_ip"`
	DstPort     uint16  `json:"dst_port"`
	SignalType  string  `json:"signal_type"`
	Severity    uint8   `json:"severity"`
	Count       uint32  `json:"count"`
	Source      string  `json:"source"`
}

func uint32ToIP(n uint32) string {
	ip := make(net.IP, 4)
	binary.LittleEndian.PutUint32(ip, n)
	return ip.String()
}

func processFraudEvents(rd *perf.Reader, fraudEndpoint string) {
	for {
		record, err := rd.Read()
		if err != nil {
			if err == perf.ErrClosed {
				return
			}
			log.Printf("Error reading perf event: %v", err)
			continue
		}

		if len(record.RawSample) < int(unsafe.Sizeof(FraudSignal{})) {
			continue
		}

		sig := (*FraudSignal)(unsafe.Pointer(&record.RawSample[0]))

		signalName, ok := signalNames[sig.SignalType]
		if !ok {
			signalName = fmt.Sprintf("unknown_%d", sig.SignalType)
		}

		// Update Prometheus metrics
		fraudSignalsTotal.WithLabelValues(
			signalName,
			fmt.Sprintf("%d", sig.Severity),
		).Inc()

		// Forward to fraud detection service
		payload := FraudEventPayload{
			TimestampNs: sig.TimestampNs,
			SrcIP:       uint32ToIP(sig.SrcIP),
			DstIP:       uint32ToIP(sig.DstIP),
			DstPort:     sig.DstPort,
			SignalType:  signalName,
			Severity:    sig.Severity,
			Count:       sig.Count,
			Source:      "ebpf_kernel",
		}

		jsonData, err := json.Marshal(payload)
		if err != nil {
			continue
		}

		// Non-blocking POST to fraud service (fire-and-forget)
		go func(data []byte) {
			ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
			defer cancel()
			req, err := http.NewRequestWithContext(ctx, "POST",
				fraudEndpoint+"/ebpf-signal",
				nil)
			if err != nil {
				return
			}
			req.Header.Set("Content-Type", "application/json")
			req.ContentLength = int64(len(data))

			client := &http.Client{}
			resp, err := client.Do(req)
			if err != nil {
				log.Printf("Failed to forward fraud signal: %v", err)
				return
			}
			resp.Body.Close()
		}(jsonData)

		log.Printf("[FRAUD SIGNAL] type=%s severity=%d src=%s dst=%s:%d count=%d",
			signalName, sig.Severity,
			uint32ToIP(sig.SrcIP), uint32ToIP(sig.DstIP), sig.DstPort,
			sig.Count)
	}
}

// ─── Metrics collector from eBPF maps ────────────────────────────────────────

func collectMetrics(metricsMap *ebpf.Map, blacklistMap *ebpf.Map) {
	ticker := time.NewTicker(10 * time.Second)
	defer ticker.Stop()

	for range ticker.C {
		// Read per-CPU metrics
		for _, key := range []MetricKey{
			MetricTotalPackets, MetricAllowedPackets,
			MetricRateLimited, MetricBlacklisted,
			MetricSynFloodBlocked, MetricWalletRequests,
		} {
			var values []uint64
			k := uint32(key)
			if err := metricsMap.Lookup(&k, &values); err != nil {
				continue
			}
			var total uint64
			for _, v := range values {
				total += v
			}

			switch key {
			case MetricTotalPackets:
				packetsTotal.WithLabelValues("total").Add(float64(total))
			case MetricAllowedPackets:
				packetsTotal.WithLabelValues("allowed").Add(float64(total))
			case MetricRateLimited:
				rateLimitedRequests.Add(float64(total))
			}
		}

		// Count blacklisted IPs
		var count float64
		var ip uint32
		var expiry uint64
		iter := blacklistMap.Iterate()
		for iter.Next(&ip, &expiry) {
			count++
		}
		blacklistedIPs.Set(count)
	}
}

// ─── Populate allowed egress map ─────────────────────────────────────────────

func populateAllowedEgressMap(m *ebpf.Map) error {
	// These are the internal service IPs that the server pod is allowed to connect to.
	// In production, these are populated from the Kubernetes service CIDR.
	// For now, we allow the entire cluster CIDR (10.0.0.0/8).
	// Cilium network policies provide the fine-grained control on top of this.
	allowedCIDRs := []string{
		"10.0.0.0/8",
		"172.16.0.0/12",
		"192.168.0.0/16",
	}

	for _, cidr := range allowedCIDRs {
		_, ipNet, err := net.ParseCIDR(cidr)
		if err != nil {
			continue
		}
		// Mark the network address as allowed (simplified — production uses LPM trie)
		ip := binary.BigEndian.Uint32(ipNet.IP.To4())
		val := uint8(1)
		if err := m.Put(&ip, &val); err != nil {
			log.Printf("Warning: could not add %s to allowed egress map: %v", cidr, err)
		}
	}
	return nil
}

// ─── Main ─────────────────────────────────────────────────────────────────────

func main() {
	iface := flag.String("iface", "eth0", "Network interface to attach XDP program")
	fraudEndpoint := flag.String("fraud-endpoint", "http://fraud-ml-service:8080", "Fraud detection service endpoint")
	metricsAddr := flag.String("metrics-addr", ":9099", "Prometheus metrics address")
	bpfFSPath := flag.String("bpf-fs", "/sys/fs/bpf/tourismpay", "BPF filesystem path for pinned maps")
	flag.Parse()

	log.Printf("TourismPay eBPF Loader starting on interface %s", *iface)

	// Remove memory lock limit (required for eBPF on Linux < 5.11)
	if err := rlimit.RemoveMemlock(); err != nil {
		log.Fatalf("Failed to remove memlock: %v", err)
	}

	// Create BPF filesystem directory for pinned maps
	if err := os.MkdirAll(*bpfFSPath, 0755); err != nil {
		log.Fatalf("Failed to create BPF FS path: %v", err)
	}

	// Load wallet rate limiter eBPF objects
	log.Println("Loading wallet_ratelimit.o eBPF program...")
	walletSpec, err := ebpf.LoadCollectionSpec("wallet_ratelimit.o")
	if err != nil {
		log.Fatalf("Failed to load wallet_ratelimit.o: %v", err)
	}

	var walletObjs WalletRatelimitObjects
	if err := walletSpec.LoadAndAssign(&walletObjs, &ebpf.CollectionOptions{
		Maps: ebpf.MapOptions{
			PinPath: *bpfFSPath,
		},
	}); err != nil {
		log.Fatalf("Failed to load wallet eBPF objects: %v", err)
	}
	defer walletObjs.WalletRateMap.Close()
	defer walletObjs.BlacklistMap.Close()
	defer walletObjs.MetricsMap.Close()

	// Load fraud detector eBPF objects
	log.Println("Loading fraud_detector.o eBPF program...")
	fraudSpec, err := ebpf.LoadCollectionSpec("fraud_detector.o")
	if err != nil {
		log.Fatalf("Failed to load fraud_detector.o: %v", err)
	}

	var fraudObjs FraudDetectorObjects
	if err := fraudSpec.LoadAndAssign(&fraudObjs, &ebpf.CollectionOptions{
		Maps: ebpf.MapOptions{
			PinPath: *bpfFSPath,
		},
	}); err != nil {
		log.Fatalf("Failed to load fraud eBPF objects: %v", err)
	}
	defer fraudObjs.FraudEvents.Close()
	defer fraudObjs.VelocityMap.Close()

	// Populate allowed egress map
	if err := populateAllowedEgressMap(fraudObjs.AllowedEgressMap); err != nil {
		log.Printf("Warning: could not populate allowed egress map: %v", err)
	}

	// Attach XDP program to network interface
	log.Printf("Attaching XDP program to %s...", *iface)
	xdpLink, err := link.AttachXDP(link.XDPOptions{
		Program:   walletObjs.TourismpaySXdpDdos,
		Interface: func() int {
			ifc, err := net.InterfaceByName(*iface)
			if err != nil {
				log.Fatalf("Interface %s not found: %v", *iface, err)
			}
			return ifc.Index
		}(),
		Flags: link.XDPGenericMode, // Use generic mode for compatibility; native mode requires driver support
	})
	if err != nil {
		log.Printf("Warning: XDP native attach failed, trying generic: %v", err)
	} else {
		defer xdpLink.Close()
		log.Printf("XDP program attached to %s in generic mode", *iface)
	}

	// Set up perf event reader for fraud signals
	rd, err := perf.NewReader(fraudObjs.FraudEvents, os.Getpagesize()*64)
	if err != nil {
		log.Fatalf("Failed to create perf reader: %v", err)
	}
	defer rd.Close()

	// Start fraud event processor
	go processFraudEvents(rd, *fraudEndpoint)

	// Start metrics collector
	go collectMetrics(walletObjs.MetricsMap, walletObjs.BlacklistMap)

	// Start Prometheus metrics server
	http.Handle("/metrics", promhttp.Handler())
	http.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"status":"ok","programs":["wallet_ratelimit","fraud_detector"]}`))
	})
	http.HandleFunc("/blacklist/add", func(w http.ResponseWriter, r *http.Request) {
		// Allow fraud service to add IPs to blacklist via HTTP
		if r.Method != http.MethodPost {
			http.Error(w, "POST only", http.StatusMethodNotAllowed)
			return
		}
		var req struct {
			IP      string `json:"ip"`
			TTLSecs int    `json:"ttl_seconds"` // 0 = permanent
		}
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		ip := net.ParseIP(req.IP).To4()
		if ip == nil {
			http.Error(w, "invalid IP", http.StatusBadRequest)
			return
		}
		ipUint32 := binary.BigEndian.Uint32(ip)
		var expiry uint64
		if req.TTLSecs > 0 {
			expiry = uint64(time.Now().Add(time.Duration(req.TTLSecs) * time.Second).UnixNano())
		}
		if err := walletObjs.BlacklistMap.Put(&ipUint32, &expiry); err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		log.Printf("Blacklisted IP %s (TTL: %ds)", req.IP, req.TTLSecs)
		w.WriteHeader(http.StatusOK)
		json.NewEncoder(w).Encode(map[string]string{"status": "blacklisted", "ip": req.IP})
	})

	go func() {
		log.Printf("Prometheus metrics on %s", *metricsAddr)
		if err := http.ListenAndServe(*metricsAddr, nil); err != nil {
			log.Fatalf("Metrics server failed: %v", err)
		}
	}()

	log.Println("eBPF programs loaded and running. Press Ctrl+C to stop.")

	// Wait for signal
	sig := make(chan os.Signal, 1)
	signal.Notify(sig, syscall.SIGINT, syscall.SIGTERM)
	<-sig

	log.Println("Shutting down eBPF loader...")
}
