apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: "kafka-0:9092,kafka-1:9092,kafka-2:9092"
  - name: consumerGroup
    value: "policy-webhook-service"
  - name: clientId
    value: "policy-webhook-service"
  - name: authType
    value: "none"
  - name: maxMessageBytes
    value: "1048576"
  - name: consumeRetryInterval
    value: "200ms"
scopes:
- policy-webhook-service
