// TypeScript enabled — Sprint 96 security audit
/**
 * Sprint 64 — Chat System Completion Module
 * F1: Typing indicators via Socket.IO
 * F2: Chat transcript PDF export
 * F3: Auto-assignment engine (round-robin + workload)
 * F4: Chat analytics (response times, resolution rates, CSAT)
 * F5: Chat search (full-text across messages and sessions)
 */

// ─── F1: Typing Indicators ──────────────────────────────────────────────────
export interface TypingEvent {
  sessionId: number;
  userId: string;
  userName: string;
  isTyping: boolean;
  timestamp: number;
}

const typingState = new Map<
  string,
  { timer: ReturnType<typeof setTimeout>; event: TypingEvent }
>();

export function handleTypingIndicator(event: TypingEvent): TypingEvent {
  const key = `${event.sessionId}:${event.userId}`;
  const existing = typingState.get(key);
  if (existing) clearTimeout(existing.timer);

  if (event.isTyping) {
    const timer = setTimeout(() => {
      typingState.delete(key);
    }, 5000); // auto-clear after 5s inactivity
    typingState.set(key, { timer, event });
  } else {
    typingState.delete(key);
  }
  return { ...event, timestamp: Date.now() };
}

export function getActiveTypers(sessionId: number): TypingEvent[] {
  const typers: TypingEvent[] = [];
  for (const [key, val] of typingState.entries()) {
    if (key.startsWith(`${sessionId}:`) && val.event.isTyping) {
      typers.push(val.event);
    }
  }
  return typers;
}

export function clearTypingState(): void {
  for (const [, val] of typingState.entries()) clearTimeout(val.timer);
  typingState.clear();
}

// ─── F2: Chat Transcript Export ─────────────────────────────────────────────
export interface TranscriptMessage {
  senderType: string;
  senderName: string;
  content: string;
  createdAt: Date | string;
}

export interface TranscriptSession {
  id: number;
  subject: string;
  category: string;
  status: string;
  agentId: string;
  supportAgentName: string | null;
  createdAt: Date | string;
  closedAt: Date | string | null;
}

export function generateTranscriptHTML(
  session: TranscriptSession,
  messages: TranscriptMessage[]
): string {
  const msgRows = messages
    .map(m => {
      const time = new Date(m.createdAt).toLocaleString();
      const senderClass =
        m.senderType === "agent"
          ? "color:#2563eb"
          : m.senderType === "admin"
            ? "color:#dc2626"
            : "color:#16a34a";
      return `<tr>
      <td style="padding:6px 10px;border-bottom:1px solid #e5e7eb;font-size:12px;color:#6b7280">${time}</td>
      <td style="padding:6px 10px;border-bottom:1px solid #e5e7eb;font-weight:600;${senderClass}">${m.senderName} (${m.senderType})</td>
      <td style="padding:6px 10px;border-bottom:1px solid #e5e7eb">${escapeHtml(m.content)}</td>
    </tr>`;
    })
    .join("\n");

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Chat Transcript #${session.id}</title>
<style>body{font-family:Arial,sans-serif;margin:40px;color:#1f2937}
h1{font-size:20px;margin-bottom:4px}
.meta{color:#6b7280;font-size:13px;margin-bottom:20px}
table{width:100%;border-collapse:collapse;font-size:13px}
th{text-align:left;padding:8px 10px;background:#f3f4f6;border-bottom:2px solid #d1d5db;font-size:12px;text-transform:uppercase;letter-spacing:0.5px}
</style></head><body>
<h1>Chat Transcript — Session #${session.id}</h1>
<div class="meta">
  <strong>Subject:</strong> ${escapeHtml(session.subject)}<br>
  <strong>Category:</strong> ${session.category} | <strong>Status:</strong> ${session.status}<br>
  <strong>Agent:</strong> ${session.agentId} | <strong>Support Agent:</strong> ${session.supportAgentName || "Unassigned"}<br>
  <strong>Opened:</strong> ${new Date(session.createdAt).toLocaleString()} |
  <strong>Closed:</strong> ${session.closedAt ? new Date(session.closedAt).toLocaleString() : "Still Open"}<br>
  <strong>Messages:</strong> ${messages.length} | <strong>Exported:</strong> ${new Date().toLocaleString()}
</div>
<table>
  <thead><tr><th>Time</th><th>Sender</th><th>Message</th></tr></thead>
  <tbody>${msgRows}</tbody>
</table>
<div style="margin-top:30px;padding-top:15px;border-top:1px solid #d1d5db;font-size:11px;color:#9ca3af">
  Generated by 54Link POS Shell — Confidential
</div>
</body></html>`;
}

export function generateTranscriptCSV(
  session: TranscriptSession,
  messages: TranscriptMessage[]
): string {
  const header = "Timestamp,Sender Type,Sender Name,Message";
  const rows = messages.map(m => {
    const time = new Date(m.createdAt).toISOString();
    const content = `"${m.content.replace(/"/g, '""')}"`;
    return `${time},${m.senderType},${m.senderName},${content}`;
  });
  return [header, ...rows].join("\n");
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

// ─── F3: Auto-Assignment Engine ─────────────────────────────────────────────
export interface SupportAgent {
  id: string;
  name: string;
  skills: string[];
  maxConcurrent: number;
  currentLoad: number;
  isAvailable: boolean;
  language?: string;
}

export type AssignmentStrategy = "round_robin" | "least_loaded" | "skill_based";

let roundRobinIndex = 0;

export function autoAssignSession(
  agents: SupportAgent[],
  strategy: AssignmentStrategy = "least_loaded",
  requiredSkill?: string,
  requiredLanguage?: string
): SupportAgent | null {
  let candidates = agents.filter(
    a => a.isAvailable && a.currentLoad < a.maxConcurrent
  );

  if (requiredSkill) {
    candidates = candidates.filter(a =>
      a.skills.some(s => s.toLowerCase() === requiredSkill.toLowerCase())
    );
  }

  if (requiredLanguage) {
    candidates = candidates.filter(
      a =>
        !a.language ||
        a.language.toLowerCase() === requiredLanguage.toLowerCase()
    );
  }

  if (candidates.length === 0) return null;

  switch (strategy) {
    case "round_robin": {
      roundRobinIndex = roundRobinIndex % candidates.length;
      const agent = candidates[roundRobinIndex];
      roundRobinIndex++;
      return agent;
    }
    case "least_loaded": {
      return candidates.reduce((min, a) =>
        a.currentLoad < min.currentLoad ? a : min
      );
    }
    case "skill_based": {
      // Prefer agents with the most matching skills
      if (requiredSkill) {
        const skilled = candidates.filter(a =>
          a.skills.includes(requiredSkill)
        );
        if (skilled.length > 0) {
          return skilled.reduce((min, a) =>
            a.currentLoad < min.currentLoad ? a : min
          );
        }
      }
      return candidates.reduce((min, a) =>
        a.currentLoad < min.currentLoad ? a : min
      );
    }
    default:
      return candidates[0] || null;
  }
}

export function resetRoundRobin(): void {
  roundRobinIndex = 0;
}

// ─── F4: Chat Analytics ─────────────────────────────────────────────────────
export interface ChatMetrics {
  totalSessions: number;
  openSessions: number;
  resolvedSessions: number;
  escalatedSessions: number;
  avgResponseTimeMs: number;
  avgResolutionTimeMs: number;
  csatAverage: number;
  csatCount: number;
  messageVolume: number;
  agentUtilization: number; // 0-1
  peakHour: number; // 0-23
  topCategories: Array<{ category: string; count: number }>;
}

export function computeChatMetrics(
  sessions: Array<{
    status: string;
    category: string;
    createdAt: Date | string;
    closedAt: Date | string | null;
    firstResponseAt: Date | string | null;
    rating: number | null;
    messageCount: number;
  }>
): ChatMetrics {
  const total = sessions.length;
  const open = sessions.filter(
    s => s.status === "open" || s.status === "assigned"
  ).length;
  const resolved = sessions.filter(
    s => s.status === "resolved" || s.status === "closed"
  ).length;
  const escalated = sessions.filter(s => s.status === "escalated").length;

  // Response times
  const responseTimes = sessions
    .filter(s => s.firstResponseAt && s.createdAt)
    .map(
      s =>
        new Date(s.firstResponseAt!).getTime() - new Date(s.createdAt).getTime()
    )
    .filter(t => t > 0);
  const avgResponseTimeMs =
    responseTimes.length > 0
      ? responseTimes.reduce((a, b) => a + b, 0) / responseTimes.length
      : 0;

  // Resolution times
  const resolutionTimes = sessions
    .filter(s => s.closedAt && s.createdAt)
    .map(s => new Date(s.closedAt!).getTime() - new Date(s.createdAt).getTime())
    .filter(t => t > 0);
  const avgResolutionTimeMs =
    resolutionTimes.length > 0
      ? resolutionTimes.reduce((a, b) => a + b, 0) / resolutionTimes.length
      : 0;

  // CSAT
  const ratings = sessions.filter(s => s.rating !== null).map(s => s.rating!);
  const csatAverage =
    ratings.length > 0
      ? ratings.reduce((a, b) => a + b, 0) / ratings.length
      : 0;

  // Message volume
  const messageVolume = sessions.reduce(
    (sum, s) => sum + (s.messageCount || 0),
    0
  );

  // Peak hour
  const hourCounts = new Array(24).fill(0);
  sessions.forEach(s => {
    const hour = new Date(s.createdAt).getHours();
    hourCounts[hour]++;
  });
  const peakHour = hourCounts.indexOf(Math.max(...hourCounts));

  // Top categories
  const catMap = new Map<string, number>();
  sessions.forEach(s => {
    catMap.set(s.category, (catMap.get(s.category) || 0) + 1);
  });
  const topCategories = Array.from(catMap.entries())
    .map(([category, count]) => ({ category, count }))
    .sort((a, b) => b.count - a.count)
    .slice(0, 5);

  // Agent utilization (ratio of assigned+open to total)
  const agentUtilization = total > 0 ? (total - open) / total : 0;

  return {
    totalSessions: total,
    openSessions: open,
    resolvedSessions: resolved,
    escalatedSessions: escalated,
    avgResponseTimeMs,
    avgResolutionTimeMs,
    csatAverage,
    csatCount: ratings.length,
    messageVolume,
    agentUtilization,
    peakHour,
    topCategories,
  };
}

// ─── F5: Chat Search ────────────────────────────────────────────────────────
export interface SearchResult {
  sessionId: number;
  subject: string;
  category: string;
  status: string;
  matchedMessages: Array<{
    messageId: number;
    content: string;
    senderName: string;
    createdAt: Date | string;
    highlight: string;
  }>;
  relevanceScore: number;
}

export function searchChatMessages(
  messages: Array<{
    id: number;
    sessionId: number;
    content: string;
    senderName: string;
    createdAt: Date | string;
  }>,
  sessions: Map<number, { subject: string; category: string; status: string }>,
  query: string,
  limit: number = 20
): SearchResult[] {
  const terms = query.toLowerCase().split(/\s+/).filter(Boolean);
  if (terms.length === 0) return [];

  const sessionMatches = new Map<number, SearchResult>();

  for (const msg of messages) {
    const contentLower = msg.content.toLowerCase();
    const matchCount = terms.filter(t => contentLower.includes(t)).length;
    if (matchCount === 0) continue;

    const relevance = matchCount / terms.length;
    const session = sessions.get(msg.sessionId);
    if (!session) continue;

    if (!sessionMatches.has(msg.sessionId)) {
      sessionMatches.set(msg.sessionId, {
        sessionId: msg.sessionId,
        subject: session.subject,
        category: session.category,
        status: session.status,
        matchedMessages: [],
        relevanceScore: 0,
      });
    }

    const result = sessionMatches.get(msg.sessionId)!;
    result.relevanceScore = Math.max(result.relevanceScore, relevance);

    // Create highlight snippet
    let highlight = msg.content;
    for (const term of terms) {
      const regex = new RegExp(`(${escapeRegex(term)})`, "gi");
      highlight = highlight.replace(regex, "**$1**");
    }

    result.matchedMessages.push({
      messageId: msg.id,
      content: msg.content,
      senderName: msg.senderName,
      createdAt: msg.createdAt,
      highlight:
        highlight.length > 200
          ? highlight.substring(0, 200) + "..."
          : highlight,
    });
  }

  return Array.from(sessionMatches.values())
    .sort((a, b) => b.relevanceScore - a.relevanceScore)
    .slice(0, limit);
}

function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
