"""
Suspicious Activity Report (SAR) Auto-Filing System

Generates and files SARs with regulatory authorities when:
  - ML risk score exceeds threshold (>0.8)
  - Transaction patterns match known typologies
  - Manual analyst escalation triggers filing
  - Structuring (smurfing) detected

Supports multiple jurisdictions:
  - Nigeria (NFIU — Nigerian Financial Intelligence Unit)
  - Kenya (FRC — Financial Reporting Centre)
  - Ghana (FIC — Financial Intelligence Centre)
  - South Africa (FIC — Financial Intelligence Centre)

FATF Travel Rule implementation:
  - Originator/beneficiary data sharing for transfers >$1000
  - IVMS101 message format (InterVASP Messaging Standard)
  - Counterparty VASP discovery and data exchange
"""
import os
import json
import hashlib
import logging
from datetime import datetime, timezone
from typing import Optional
from dataclasses import dataclass, asdict
from enum import Enum

import httpx
from pydantic import BaseModel, Field

logger = logging.getLogger("tourismpay.compliance.sar")

# ─── Configuration ────────────────────────────────────────────────────────────

NFIU_API_URL = os.getenv("NFIU_API_URL", "")
NFIU_API_KEY = os.getenv("NFIU_API_KEY", "")
FRC_API_URL = os.getenv("FRC_KENYA_API_URL", "")
FRC_API_KEY = os.getenv("FRC_KENYA_API_KEY", "")
FIC_GH_API_URL = os.getenv("FIC_GHANA_API_URL", "")
FIC_ZA_API_URL = os.getenv("FIC_SOUTHAFRICA_API_URL", "")
DATABASE_URL = os.getenv("DATABASE_URL", "postgresql://tourismpay_user:testpass123@localhost:5432/tourismpay")

TRAVEL_RULE_THRESHOLD_USD = 1000.0
SAR_AUTO_FILE_THRESHOLD = 0.8


# ─── Models ───────────────────────────────────────────────────────────────────

class Jurisdiction(str, Enum):
    NIGERIA = "NG"
    KENYA = "KE"
    GHANA = "GH"
    SOUTH_AFRICA = "ZA"
    TANZANIA = "TZ"
    UGANDA = "UG"


class SARCategory(str, Enum):
    STRUCTURING = "structuring"
    UNUSUAL_ACTIVITY = "unusual_activity"
    TERRORISM_FINANCING = "terrorism_financing"
    MONEY_LAUNDERING = "money_laundering"
    FRAUD = "fraud"
    TAX_EVASION = "tax_evasion"
    SANCTIONS_VIOLATION = "sanctions_violation"
    PEP_TRANSACTION = "pep_transaction"


class SARRequest(BaseModel):
    subject_id: str
    subject_name: str
    subject_type: str = "individual"  # individual | business
    jurisdiction: Jurisdiction
    category: SARCategory
    narrative: str
    transaction_ids: list[str] = Field(default_factory=list)
    total_amount: float = 0.0
    currency: str = "NGN"
    risk_score: float = 0.0
    detection_method: str = "ml_auto"  # ml_auto | rule_based | analyst_referral
    supporting_evidence: dict = Field(default_factory=dict)


class SARResponse(BaseModel):
    sar_id: str
    filing_reference: Optional[str] = None
    status: str  # filed | pending | failed | queued
    jurisdiction: str
    filed_at: Optional[str] = None
    regulatory_body: str
    acknowledgement_id: Optional[str] = None


class TravelRuleMessage(BaseModel):
    """IVMS101-compliant travel rule message"""
    message_id: str
    originator: dict  # {name, account_id, address, country, date_of_birth, national_id}
    beneficiary: dict  # {name, account_id, institution_name, country}
    originating_vasp: dict  # {name, lei, country}
    beneficiary_vasp: dict  # {name, lei, country}
    transfer_amount: float
    transfer_currency: str
    transfer_id: str
    timestamp: str


# ─── SAR Generation ───────────────────────────────────────────────────────────

def generate_sar_narrative(
    subject_name: str,
    category: SARCategory,
    transactions: list[dict],
    risk_indicators: list[str],
) -> str:
    """Generate structured SAR narrative following NFIU/FRC formatting requirements."""
    lines = [
        f"SUSPICIOUS ACTIVITY REPORT",
        f"Subject: {subject_name}",
        f"Category: {category.value}",
        f"Date Generated: {datetime.now(timezone.utc).isoformat()}",
        f"",
        f"SUMMARY OF SUSPICIOUS ACTIVITY:",
        f"The following activity has been identified as potentially suspicious based on "
        f"automated monitoring systems and risk scoring algorithms.",
        f"",
        f"RISK INDICATORS:",
    ]

    for i, indicator in enumerate(risk_indicators, 1):
        lines.append(f"  {i}. {indicator}")

    lines.extend([
        f"",
        f"TRANSACTION DETAILS:",
        f"Total transactions flagged: {len(transactions)}",
    ])

    total_amount = sum(t.get("amount", 0) for t in transactions)
    lines.append(f"Total value: {total_amount:,.2f}")

    if transactions:
        lines.append(f"Date range: {transactions[0].get('date', 'N/A')} to {transactions[-1].get('date', 'N/A')}")

    lines.extend([
        f"",
        f"RECOMMENDATION:",
        f"This report has been auto-generated by TourismPay's compliance monitoring system. "
        f"The risk scoring model (version 2.0) assigned a score exceeding the filing threshold.",
    ])

    return "\n".join(lines)


async def file_sar(request: SARRequest) -> SARResponse:
    """File a SAR with the appropriate regulatory authority."""
    sar_id = f"SAR-{request.jurisdiction.value}-{datetime.now(timezone.utc).strftime('%Y%m%d')}-{hashlib.sha256(request.subject_id.encode()).hexdigest()[:8]}"

    # Determine regulatory body and API
    reg_config = {
        Jurisdiction.NIGERIA: ("NFIU", NFIU_API_URL, NFIU_API_KEY),
        Jurisdiction.KENYA: ("FRC", FRC_API_URL, FRC_API_KEY),
        Jurisdiction.GHANA: ("FIC-GH", FIC_GH_API_URL, ""),
        Jurisdiction.SOUTH_AFRICA: ("FIC-ZA", FIC_ZA_API_URL, ""),
    }

    reg_body, api_url, api_key = reg_config.get(request.jurisdiction, ("UNKNOWN", "", ""))

    # Persist SAR locally first (always succeeds)
    sar_record = {
        "sar_id": sar_id,
        "subject_id": request.subject_id,
        "subject_name": request.subject_name,
        "jurisdiction": request.jurisdiction.value,
        "category": request.category.value,
        "narrative": request.narrative,
        "total_amount": request.total_amount,
        "currency": request.currency,
        "risk_score": request.risk_score,
        "detection_method": request.detection_method,
        "regulatory_body": reg_body,
        "created_at": datetime.now(timezone.utc).isoformat(),
    }

    # Attempt to file with regulatory API
    filing_reference = None
    acknowledgement_id = None
    status = "queued"

    if api_url and api_key:
        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.post(
                    f"{api_url}/api/v1/sar/submit",
                    headers={
                        "Authorization": f"Bearer {api_key}",
                        "Content-Type": "application/json",
                        "X-Reporting-Entity": "TourismPay-DFSP",
                    },
                    json={
                        "report_type": "SAR",
                        "subject": {
                            "name": request.subject_name,
                            "id_type": "platform_id",
                            "id_value": request.subject_id,
                            "type": request.subject_type,
                        },
                        "category": request.category.value,
                        "narrative": request.narrative,
                        "transactions": request.transaction_ids,
                        "total_value": request.total_amount,
                        "currency": request.currency,
                    },
                )

                if response.status_code in (200, 201, 202):
                    result = response.json()
                    filing_reference = result.get("reference_number")
                    acknowledgement_id = result.get("acknowledgement_id")
                    status = "filed"
                    logger.info(f"SAR {sar_id} filed successfully with {reg_body}: {filing_reference}")
                else:
                    status = "pending"
                    logger.warning(f"SAR {sar_id} filing returned {response.status_code}: {response.text}")

        except Exception as e:
            status = "pending"
            logger.error(f"SAR {sar_id} filing failed (will retry): {e}")
    else:
        # No API configured — queue for manual submission
        status = "queued"
        logger.info(f"SAR {sar_id} queued (no {reg_body} API configured)")

    return SARResponse(
        sar_id=sar_id,
        filing_reference=filing_reference,
        status=status,
        jurisdiction=request.jurisdiction.value,
        filed_at=datetime.now(timezone.utc).isoformat() if status == "filed" else None,
        regulatory_body=reg_body,
        acknowledgement_id=acknowledgement_id,
    )


# ─── FATF Travel Rule ────────────────────────────────────────────────────────

async def create_travel_rule_message(
    transfer_id: str,
    originator: dict,
    beneficiary: dict,
    amount: float,
    currency: str,
) -> TravelRuleMessage:
    """
    Create IVMS101-compliant travel rule message for cross-border transfers >$1000.

    Per FATF Recommendation 16, VASPs must:
    1. Collect originator information (name, account, address, national ID)
    2. Collect beneficiary information (name, account, institution)
    3. Exchange this information with the counterparty VASP
    4. Retain records for 5+ years
    """
    message_id = f"TR-{hashlib.sha256(transfer_id.encode()).hexdigest()[:12]}"

    message = TravelRuleMessage(
        message_id=message_id,
        originator={
            "name": originator.get("name", ""),
            "account_id": originator.get("account_id", ""),
            "address": originator.get("address", ""),
            "country": originator.get("country", ""),
            "date_of_birth": originator.get("dob", ""),
            "national_id": originator.get("national_id", ""),
        },
        beneficiary={
            "name": beneficiary.get("name", ""),
            "account_id": beneficiary.get("account_id", ""),
            "institution_name": beneficiary.get("institution", "TourismPay"),
            "country": beneficiary.get("country", ""),
        },
        originating_vasp={
            "name": "TourismPay Limited",
            "lei": os.getenv("TOURISMPAY_LEI", ""),
            "country": originator.get("country", "NG"),
        },
        beneficiary_vasp={
            "name": beneficiary.get("vasp_name", "TourismPay Limited"),
            "lei": beneficiary.get("vasp_lei", os.getenv("TOURISMPAY_LEI", "")),
            "country": beneficiary.get("country", ""),
        },
        transfer_amount=amount,
        transfer_currency=currency,
        transfer_id=transfer_id,
        timestamp=datetime.now(timezone.utc).isoformat(),
    )

    logger.info(f"Travel rule message created: {message_id} for transfer {transfer_id} ({amount} {currency})")
    return message


async def should_apply_travel_rule(amount_usd: float) -> bool:
    """Check if transfer amount exceeds FATF travel rule threshold."""
    return amount_usd >= TRAVEL_RULE_THRESHOLD_USD


async def exchange_travel_rule_data(message: TravelRuleMessage, counterparty_endpoint: str) -> dict:
    """Exchange IVMS101 data with counterparty VASP."""
    if not counterparty_endpoint:
        logger.info(f"No counterparty endpoint for travel rule message {message.message_id} — stored locally")
        return {"status": "stored_locally", "message_id": message.message_id}

    try:
        async with httpx.AsyncClient(timeout=15.0) as client:
            response = await client.post(
                counterparty_endpoint,
                headers={"Content-Type": "application/json", "X-Protocol": "IVMS101"},
                json=asdict(message) if hasattr(message, "__dataclass_fields__") else message.model_dump(),
            )
            if response.status_code in (200, 201, 202):
                return {"status": "exchanged", "message_id": message.message_id, "response": response.json()}
            else:
                return {"status": "failed", "message_id": message.message_id, "error": response.text}
    except Exception as e:
        logger.error(f"Travel rule exchange failed for {message.message_id}: {e}")
        return {"status": "failed", "message_id": message.message_id, "error": str(e)}
