---
apiVersion: v1
kind: Namespace
metadata:
  name: tourismpay
  labels:
    app.kubernetes.io/part-of: tourismpay
    istio-injection: enabled
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: "[]"
