apiVersion: v1
kind: Namespace
metadata:
  name: insurance-platform
  labels:
    app.kubernetes.io/name: insurance-platform
    app.kubernetes.io/part-of: unified-insurance-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: middleware
  labels:
    app.kubernetes.io/name: middleware
    app.kubernetes.io/part-of: unified-insurance-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/part-of: unified-insurance-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  labels:
    app.kubernetes.io/name: ingress
    app.kubernetes.io/part-of: unified-insurance-platform
